# Generated by Django 3.2.4 on 2021-10-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Todos',
        ),
    ]
