# Generated by Django 3.2.8 on 2021-10-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_rename_todos_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='id',
            new_name='task_id',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
    ]
